USE [master]
GO

/****** Object:  Database [DWH_INTERMIDIATE]    Script Date: 27/5/2023 1:38:38 πμ ******/
CREATE DATABASE [DWH_INTERMIDIATE]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DWH_LEGACY', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\DWH_LEGACY.mdf' , SIZE = 401408KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DWH_LEGACY_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\DWH_LEGACY_log.ldf' , SIZE = 7151616KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DWH_INTERMIDIATE].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DWH_INTERMIDIATE] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DWH_INTERMIDIATE] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DWH_INTERMIDIATE] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DWH_INTERMIDIATE] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DWH_INTERMIDIATE] SET ARITHABORT OFF 
GO

ALTER DATABASE [DWH_INTERMIDIATE] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DWH_INTERMIDIATE] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DWH_INTERMIDIATE] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DWH_INTERMIDIATE] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DWH_INTERMIDIATE] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DWH_INTERMIDIATE] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DWH_INTERMIDIATE] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DWH_INTERMIDIATE] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DWH_INTERMIDIATE] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DWH_INTERMIDIATE] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DWH_INTERMIDIATE] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DWH_INTERMIDIATE] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DWH_INTERMIDIATE] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DWH_INTERMIDIATE] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DWH_INTERMIDIATE] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DWH_INTERMIDIATE] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DWH_INTERMIDIATE] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DWH_INTERMIDIATE] SET RECOVERY FULL 
GO

ALTER DATABASE [DWH_INTERMIDIATE] SET  MULTI_USER 
GO

ALTER DATABASE [DWH_INTERMIDIATE] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DWH_INTERMIDIATE] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DWH_INTERMIDIATE] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DWH_INTERMIDIATE] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DWH_INTERMIDIATE] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DWH_INTERMIDIATE] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [DWH_INTERMIDIATE] SET QUERY_STORE = ON
GO

ALTER DATABASE [DWH_INTERMIDIATE] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [DWH_INTERMIDIATE] SET  READ_WRITE 
GO


